/**
 * AGIRIGHT Integration Conformance Profile v0.1 §22 — Terminology Lint.
 *
 * Scans this site's own source content for bare "AICL" (no -C or -I suffix)
 * that isn't resolvable from immediate context, and flags TERM_AMBIGUITY.
 * A bare "AICL" is considered resolved if the same line (or the file
 * overall, for prose files) also mentions AICL-C, AICL-I, "Content
 * Licensing", or "Ingestion" nearby -- i.e. a human or a naming-note
 * sentence has already disambiguated it.
 *
 *   node scripts/terminology-lint.mjs
 *
 * Writes public/ai/terminology-lint-report.json with the actual scan
 * result -- generated from this run, not hand-typed.
 */
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { join, dirname, extname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const ROOT = join(here, '..');
const OUT = join(ROOT, 'public', 'ai', 'terminology-lint-report.json');

const SCAN_DIRS = [
  join(ROOT, 'src', 'content', 'whitepapers'),
  join(ROOT, 'src', 'data'),
];
const EXTENSIONS = new Set(['.md', '.ts']);

function walk(dir) {
  const out = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    const stat = statSync(full);
    if (stat.isDirectory()) out.push(...walk(full));
    else if (EXTENSIONS.has(extname(full))) out.push(full);
  }
  return out;
}

const files = SCAN_DIRS.flatMap(walk);

// A bare AICL occurrence: "AICL" not immediately followed by -C or -I,
// and not part of a longer identifier like AICL-I/AICL-C already matched
// elsewhere on the same line.
const BARE_AICL = /\bAICL\b(?!-[CI])/g;
const DISAMBIGUATION_HINTS = /(AICL-C|AICL-I|Content Licens|Ingestion|攝取|內容授權|消歧義|disambiguat)/i;

const findings = [];

for (const file of files) {
  const text = readFileSync(file, 'utf8');
  const lines = text.split('\n');
  const fileHasHint = DISAMBIGUATION_HINTS.test(text);
  lines.forEach((line, idx) => {
    const matches = line.match(BARE_AICL);
    if (!matches) return;
    const lineHasHint = DISAMBIGUATION_HINTS.test(line);
    // Ambiguous only if NEITHER the line NOR the whole file disambiguates it.
    // A whitepaper that states its own AICL meaning once at the top and
    // then uses the bare form throughout is not ambiguous in context.
    if (!lineHasHint && !fileHasHint) {
      findings.push({
        file: file.replace(ROOT + '\\', '').replace(/\\/g, '/'),
        line: idx + 1,
        excerpt: line.trim().slice(0, 160),
        status: 'TERM_AMBIGUITY',
      });
    }
  });
}

// Findings this scan surfaces but that are intentionally NOT auto-fixed --
// documented here (not filtered out of `findings` above) so the report
// stays honest: the raw scan result is never silently cleaned up to look
// like a pass.
const KNOWN_EXCEPTIONS = [
  {
    pattern: 'src/content/whitepapers/aars-agent-action-rights-spectrum.md',
    reason:
      'AARS v0.1 is a published third-party-authored paper (Neo.K / EveMissLab) predating the 2026-08-15 AICL-I v0.2 naming disambiguation. Its own text is frozen at v0.1 publication and is not this integration\'s content to silently rewrite; a future AARS patch document would need to address this, the same way the v0.1.1 patches did for AIRS/AILP/AICR/AICL.',
  },
  {
    pattern: 'src/data/examples.ts',
    reason:
      'The literal JSON field value "protocol": "AICL" matches this site\'s actual, unchanged protocol identifier (id: \'aicl\' in protocols.ts) -- renaming it to "AICL-C" here would make the example inconsistent with every other AICL reference on the site. The AICL-I v0.2 paper itself says human-facing prose MAY use the bare form where context is unambiguous (a policy-example "catalog" titled after a licensing schema is such a context).',
  },
];

const report = {
  report_version: '0.1',
  publisher: 'AGIRight.org',
  check: 'terminology_lint',
  profile_reference: 'AGIRIGHT Integration & Conformance Profile v0.1 §22',
  files_scanned: files.length,
  ambiguities_found: findings.length,
  findings,
  known_exceptions: KNOWN_EXCEPTIONS,
  status: findings.length === 0 ? 'PASS' : 'NEEDS_REVIEW',
  note: 'Scans src/content/whitepapers/*.md and src/data/*.ts for bare "AICL" without a -C/-I suffix or nearby disambiguation hint (AICL-C, AICL-I, "Content Licensing", "Ingestion", or the corresponding Chinese terms). Generated by scripts/terminology-lint.mjs. Findings are reported as-is, not filtered by known_exceptions -- see that field for why each remaining finding was left unfixed rather than treated as a false negative.',
};

writeFileSync(OUT, JSON.stringify(report, null, 2) + '\n', 'utf8');
console.log(`Files scanned: ${report.files_scanned}`);
console.log(`Ambiguities found: ${report.ambiguities_found}`);
console.log(`Status: ${report.status}`);
